import { lib, game, ui, get, ai, _status } from "../../../../noname.js";

export const characters = {
	芙宁娜芙卡洛斯: {
		sex: "female",
		group: "shen",
		hp: 3,
		skills: ["ffshenqu", "ffduwu", "ffshenpan"],
		names: "null|芙宁娜-null|芙卡洛斯",
		img: "extension/奥特之星/assets/image/芙宁娜芙卡洛斯.jpg",
	},
	那维莱特: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["nwlthailang", "nwltgongzheng", "nwltjuecai"],
		names: "那维莱特|null",
		img: "extension/奥特之星/assets/image/那维莱特.jpg",
		dieAudios: ["ext:奥特之星/assets/audio/那维莱特.mp3"],
	},
	阿蕾奇诺: {
		sex: "female",
		group: "shen",
		hp: 4,
		skills: ["alqnhuahui", "alqnzhanshou", "alqneyue"],
		names: "null|佩露薇利",
		img: "extension/奥特之星/assets/image/阿蕾奇诺.jpg",
		dieAudios: ["ext:奥特之星/assets/audio/阿蕾奇诺.mp3"],
	},
	丝柯克: {
		sex: "female",
		group: "shen",
		hp: 4,
		skills: ["skkjimie", "skkduduan"],
		img: "extension/奥特之星/assets/image/丝柯克.jpg",
		dieAudios: ["ext:奥特之星/assets/audio/丝柯克.mp3"],
	},
	芙宁娜: {
		sex: "female",
		group: "shen",
		hp: 5,
		skills: ["ffshalong", "ffyuanwu", "ffkuanghuan"],
		names: "null|芙宁娜",
		img: "extension/奥特之星/assets/image/芙宁娜.jpg",
		dieAudios: ["ext:奥特之星/assets/audio/芙宁娜.mp3"],
	},
	恰斯卡: {
		sex: "female",
		group: "shen",
		hp: 3,
		skills: ["qsklingjiang", "qsksuohun"],
		names: "null|恰斯卡",
		img: "extension/奥特之星/assets/image/恰斯卡.jpg",
		dieAudios: ["ext:奥特之星/assets/audio/恰斯卡.mp3"],
	},
	玛薇卡: {
		sex: "female",
		group: "shen",
		hp: 4,
		skills: ["mwkzhihuo", "mwkfenyao", "mwkfantian"],
		names: "null|玛薇卡",
		img: "extension/奥特之星/assets/image/玛薇卡.jpg",
		dieAudios: ["ext:奥特之星/assets/audio/玛薇卡.mp3"],
	},
	希诺宁: {
		sex: "female",
		group: "shen",
		hp: 4,
		skills: ["xnnjuelie", "xnnduancui"],
		names: "null|希诺宁",
		img: "extension/奥特之星/assets/image/希诺宁.jpg",
		dieAudios: ["ext:奥特之星/assets/audio/希诺宁.mp3"],
	},
};
