import { lib, game, ui, get, ai, _status } from "../../../../noname.js";

export const characters = {
	流萤: {
		sex: "female",
		group: "shen",
		hp: 5,
		skills: ["lyshishang", "lyranjin", "lyyuhuo"],
		names: "null|流萤",
		img: "extension/奥特之星/assets/流萤.jpg",
		dieAudios: ["ext:奥特之星/assets/流萤.mp3"],
	},
	大丽花: {
		sex: "female",
		group: "shen",
		hp: 4,
		skills: ["dlhchizhuo"],
		names: "null|大丽花",
		img: "extension/奥特之星/assets/大丽花.jpg",
		dieAudios: ["ext:奥特之星/assets/大丽花.mp3"],
	},
	忘归人: {
		sex: "female",
		group: "shen",
		hp: 4,
		skills: ["wgryanzhao"],
		names: "null|忘归人",
		img: "extension/奥特之星/assets/忘归人.jpg",
		dieAudios: ["ext:奥特之星/assets/忘归人.mp3"],
	},
	灵砂: {
		sex: "female",
		group: "shen",
		hp: 4,
		skills: ["lszhuoyan", "lsfenyun"],
		names: "null|灵砂",
		img: "extension/奥特之星/assets/灵砂.jpg",
		dieAudios: ["ext:奥特之星/assets/灵砂.mp3"],
	},
	知更鸟: {
		sex: "female",
		group: "shen",
		hp: 3,
		skills: ["zgnxiezou"],
		names: "null|知更鸟",
		img: "extension/奥特之星/assets/知更鸟.jpg",
		dieAudios: ["ext:奥特之星/assets/知更鸟.mp3"],
	},
	云璃: {
		sex: "female",
		group: "shen",
		hp: 4,
		skills: ["ylshanshuo", "ylxiahe", "ylkanpo"],
		img: "extension/奥特之星/assets/云璃.jpg",
		dieAudios: ["ext:奥特之星/assets/云璃.mp3"],
	},
	遐蝶: {
		sex: "female",
		group: "shen",
		hp: 10,
		skills: ["xdanchao", "xdyuejian", "xdyoudie"],
		names: "null|遐蝶",
		img: "extension/奥特之星/assets/遐蝶.jpg",
		dieAudios: ["ext:奥特之星/assets/遐蝶.mp3"],
	},
	黄泉: {
		sex: "female",
		group: "shen",
		hp: 4,
		skills: ["hqchigui", "hqtize"],
		names: "雷电忘川守|芽衣",
		img: "extension/奥特之星/assets/黄泉.jpg",
		dieAudios: ["ext:奥特之星/assets/黄泉.mp3"],
	},
};
