import { lib, game, ui, get, ai, _status } from "../../../../../noname.js";

export const characters = {
	奈克瑟斯: {
		sex: "male",
		group: "ao_red",
		hp: 4,
		skills: ["nkssjicheng"],
		names: "null|奈克瑟斯",
		img: "extension/奥特之星/assets/ultraman/image/奈克瑟斯.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/奈克瑟斯.mp3"],
	},
	闪耀迪迦: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["sydjqiji", "sydjhuihuang"],
		names: "null|迪迦",
		img: "extension/奥特之星/assets/ultraman/image/闪耀迪迦.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/那位大人.mp3"],
	},
	迪迦: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["djsj"],
		names: "null|迪迦",
		img: "extension/奥特之星/assets/ultraman/image/迪迦-复合.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/迪迦.mp3"],
	},
	黑暗迪迦: {
		sex: "male",
		group: "ao_black",
		hp: 4,
		skills: ["hadjheian", "hadjanrong", "hadjyihui"],
		names: "null|迪迦",
		img: "extension/奥特之星/assets/ultraman/image/黑暗迪迦.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/黑暗迪迦.mp3"],
	},
	赛迦: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["sjyuzhi", "sjzhanren"],
		names: "null|赛迦",
		img: "extension/奥特之星/assets/ultraman/image/赛迦.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/那位大人.mp3"],
	},
	希卡利: {
		sex: "male",
		group: "ao",
		hp: 3,
		skills: ["xklkeyan", "xkllizhu"],
		names: "null|希卡利",
		img: "extension/奥特之星/assets/ultraman/image/希卡利.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/希卡利.mp3"],
	},
	戴拿: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["dnshuijing"],
		names: "null|戴拿",
		img: "extension/奥特之星/assets/ultraman/image/戴拿-闪亮.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/戴拿.mp3"],
	},
	至高盖亚: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["zggylianshuai", "zggyjili"],
		names: "null|盖亚",
		img: "extension/奥特之星/assets/ultraman/image/至高盖亚.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/那位大人.mp3"],
	},
	杰斯提斯: {
		sex: "none",
		group: "ao",
		hp: 4,
		skills: ["jstsfensui"],
		names: "null|杰斯提斯",
		img: "extension/奥特之星/assets/ultraman/image/杰斯提斯.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/那位大人.mp3"],
	},
};
