import { lib, game, ui, get, ai, _status } from "../../../../../noname.js";

export const characters = {
	安培拉星人: {
		sex: "male",
		group: "yv",
		hp: 5,
		skills: ["aplxiongye", "aplaojie"],
		names: "null|安培拉星人",
		img: "extension/奥特之星/assets/ultraman/image/安培拉星人.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/安培拉星人.mp3"],
	},
	奥特之父: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["atzfzhenli", "atzfchiyuan"],
		names: "null|健",
		img: "extension/奥特之星/assets/ultraman/image/奥特之父.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/奥特之父.mp3"],
	},
	奥特之王: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["atzwxingmian", "atzwbuxi"],
		names: "null|皮特",
		img: "extension/奥特之星/assets/ultraman/image/奥特之王.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/那位大人.mp3"],
	},
	奥特曼: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["atmguanglun", "atmzhuangshuo", "atmnianli"],
		names: "null|奥特曼",
		img: "extension/奥特之星/assets/ultraman/image/奥特曼.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/那位大人.mp3"],
	},
	杰克: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["jkshouzhuo", "jkjuedi", "atmnianli"],
		names: "null|杰克",
		img: "extension/奥特之星/assets/ultraman/image/杰克.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/杰克.mp3"],
	},
	佐菲: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["zfbaqi", "zfyakong", "atmnianli"],
		names: "null|佐菲",
		img: "extension/奥特之星/assets/ultraman/image/佐菲.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/佐菲.mp3"],
	},
	泰罗: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["tlpoquan", "tlzhadan", "atmnianli"],
		names: "null|泰罗",
		img: "extension/奥特之星/assets/ultraman/image/泰罗.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/泰罗.mp3"],
	},
	艾斯: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["asguangxian", "asduantou", "atmnianli"],
		names: "null|艾斯",
		img: "extension/奥特之星/assets/ultraman/image/艾斯.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/那位大人.mp3"],
	},
	赛文: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["swbingfu", "swxiongjia", "atmnianli"],
		names: "null|赛文",
		img: "extension/奥特之星/assets/ultraman/image/赛文.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/那位大人.mp3"],
	},
	雷欧: {
		sex: "male",
		group: "ao_red",
		hp: 4,
		maxHp: 5,
		skills: ["leofenzhan", "leofeiti"],
		names: "null|雷欧",
		img: "extension/奥特之星/assets/ultraman/image/雷欧.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/那位大人.mp3"],
	},
	爱迪: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["adkoudai", "adquanneng", "adjinghua"],
		names: "null|爱迪",
		img: "extension/奥特之星/assets/ultraman/image/爱迪.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/那位大人.mp3"],
	},
	阿斯特拉: {
		sex: "male",
		group: "ao_red",
		hp: 4,
		skills: ["astlqiuyv", "leofenzhan", "leofeiti"],
		names: "null|阿斯特拉",
		img: "extension/奥特之星/assets/ultraman/image/阿斯特拉.jpg",
		dieAudios: ["ext:奥特之星/assets/ultraman/audio/die/那位大人.mp3"],
	}
};
