import { lib, game, ui, get, ai, _status } from "../../../../../../noname.js";

export const characters = {
	奈克瑟斯: {
		sex: "male",
		group: "ao_red",
		hp: 4,
		skills: ["nkssjicheng"],
		names: "null|奈克瑟斯",
		img: "extension/奥特之星/assets/奈克瑟斯.jpg",
		dieAudios: ["ext:奥特之星/assets/奈克瑟斯.mp3"],
	},
	迪迦: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["djsj"],
		names: "null|迪迦",
		img: "extension/奥特之星/assets/迪迦-复合.jpg",
		dieAudios: ["ext:奥特之星/assets/迪迦.mp3"],
	},
	希卡利: {
		sex: "male",
		group: "ao",
		hp: 3,
		skills: ["xklkeyan", "xkllizhu"],
		names: "null|希卡利",
		img: "extension/奥特之星/assets/希卡利.jpg",
		dieAudios: ["ext:奥特之星/assets/希卡利.mp3"],
	},
	奥特曼: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["atmguanglun", "atmzhuangshuo", "atmnianli"],
		names: "null|奥特曼",
		img: "extension/奥特之星/assets/奥特曼.jpg",
		dieAudios: ["ext:奥特之星/assets/那位大人.mp3"],
	},
	杰克: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["jkshouzhuo", "jkjuedi", "atmnianli"],
		names: "null|杰克",
		img: "extension/奥特之星/assets/杰克.jpg",
		dieAudios: ["ext:奥特之星/assets/杰克.mp3"],
	},
	戴拿: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["dnshuijing"],
		names: "null|戴拿",
		img: "extension/奥特之星/assets/戴拿-闪亮.jpg",
		dieAudios: ["ext:奥特之星/assets/戴拿.mp3"],
	},
	佐菲: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["zfbaqi", "zfyakong", "atmnianli"],
		names: "null|佐菲",
		img: "extension/奥特之星/assets/佐菲.jpg",
		dieAudios: ["ext:奥特之星/assets/佐菲.mp3"],
	},
	泰罗: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["tlpoquan", "tlzhadan", "atmnianli"],
		names: "null|泰罗",
		img: "extension/奥特之星/assets/泰罗.jpg",
		dieAudios: ["ext:奥特之星/assets/泰罗.mp3"],
	},
	艾斯: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["asguangxian", "asduantou", "atmnianli"],
		names: "null|艾斯",
		img: "extension/奥特之星/assets/艾斯.jpg",
		dieAudios: ["ext:奥特之星/assets/那位大人.mp3"],
	},
	赛文: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["swbingfu", "swxiongjia", "atmnianli"],
		names: "null|赛文",
		img: "extension/奥特之星/assets/赛文.jpg",
		dieAudios: ["ext:奥特之星/assets/那位大人.mp3"],
	},
	雷欧: {
		sex: "male",
		group: "ao_red",
		hp: 4,
		maxHp: 5,
		skills: ["leofenzhan", "leofeiti"],
		names: "null|雷欧",
		img: "extension/奥特之星/assets/雷欧.jpg",
		dieAudios: ["ext:奥特之星/assets/那位大人.mp3"],
	},
	杰斯提斯: {
		sex: "none",
		group: "ao",
		hp: 4,
		skills: ["jstsfensui"],
		names: "null|杰斯提斯",
		img: "extension/奥特之星/assets/杰斯提斯.jpg",
		dieAudios: ["ext:奥特之星/assets/那位大人.mp3"],
	},
	爱迪: {
		sex: "male",
		group: "ao",
		hp: 4,
		skills: ["adkoudai", "adquanneng", "adjinghua"],
		names: "null|爱迪",
		img: "extension/奥特之星/assets/爱迪.jpg",
		dieAudios: ["ext:奥特之星/assets/那位大人.mp3"],
	},
	阿斯特拉: {
		sex: "male",
		group: "ao_red",
		hp: 4,
		skills: ["astlqiuyv", "leofenzhan", "leofeiti"],
		names: "null|阿斯特拉",
		img: "extension/奥特之星/assets/阿斯特拉.jpg",
		dieAudios: ["ext:奥特之星/assets/那位大人.mp3"],
	},
};
